# Generated by Django 5.2.15 on 2026-06-17 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_sales_pipeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='duplicate_checked',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='duplicate_customer_no',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='original_assigned_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='employee_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='responsible_region',
        ),
        migrations.AddField(
            model_name='contactlog',
            name='feishu_record_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='contactlog',
            name='feishu_source_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contactlog',
            name='follower_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contactlog',
            name='minutes_link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='contactlog',
            name='photo_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='contract',
            name='feishu_app_token',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='contract',
            name='feishu_record_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='contract',
            name='feishu_source_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contract',
            name='feishu_table_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_by_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='attachment_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_status_text',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='duplicate_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='duplicate_customer_no',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='customer',
            name='feishu_app_token',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='customer',
            name='feishu_record_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='customer',
            name='feishu_source_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='feishu_table_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='customer',
            name='lead_no',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='customer',
            name='lead_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='legacy_customer_no',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='customer',
            name='original_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='owner_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='source_kind',
            field=models.CharField(choices=[('lead', '线索'), ('customer', '客户')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_no',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='FeishuSyncSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('source_type', models.CharField(choices=[('base', '多维表格'), ('sheet', '电子表格')], default='base', max_length=20)),
                ('app_token', models.CharField(max_length=128)),
                ('table_id', models.CharField(max_length=64)),
                ('sheet_id', models.CharField(blank=True, max_length=64)),
                ('sheet_range', models.CharField(blank=True, max_length=64)),
                ('source_kind', models.CharField(choices=[('customer', '客户/线索'), ('contact_log', '跟进记录'), ('contract', '合同')], default='customer', max_length=20)),
                ('default_record_kind', models.CharField(choices=[('lead', '线索'), ('customer', '客户')], default='lead', max_length=20)),
                ('field_mapping', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_result', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('app_token', 'table_id', 'sheet_id', 'source_kind')},
            },
        ),
        migrations.CreateModel(
            name='FeishuSyncRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=64)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('raw_fields', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('contact_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feishu_sync_records', to='crm.contactlog')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feishu_sync_records', to='crm.contract')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feishu_sync_records', to='crm.customer')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='crm.feishusyncsource')),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'unique_together': {('source', 'record_id')},
            },
        ),
        migrations.DeleteModel(
            name='Opportunity',
        ),
    ]
