# Generated by Django 5.2.15 on 2026-06-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_contract_opportunity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlog',
            name='source',
            field=models.CharField(choices=[('manual', '人工录入'), ('xiaoquan', 'CRM助手整理'), ('feishu', '飞书同步'), ('import', '批量导入')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='account_source',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.FileField(blank=True, upload_to='customer_images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='related_lead',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
