# Generated by Django 5.2.15 on 2026-06-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_contactlog_source_customer_account_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_status_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='demand',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='grade',
            field=models.CharField(choices=[('incubating', '待孵化客户'), ('potential', '潜在客户'), ('normal', '一般客户'), ('intention', '意向客户'), ('key', '重点客户'), ('uncertain', '待定客户'), ('invalid', '无效客户')], default='potential', max_length=20),
        ),
    ]
