# Generated by Django 5.2.15 on 2026-06-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_customer_customer_status_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedCustomerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=64)),
                ('original_customer_id', models.BigIntegerField()),
                ('customer_no', models.CharField(blank=True, db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('source_kind', models.CharField(blank=True, max_length=20)),
                ('reason', models.CharField(blank=True, max_length=160)),
                ('payload', models.JSONField(default=dict)),
                ('related_payload', models.JSONField(blank=True, default=dict)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-archived_at', 'customer_no'],
            },
        ),
    ]
