# Generated by Django 5.2.15 on 2026-06-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_archivedcustomersnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlog',
            name='photo_file',
            field=models.FileField(blank=True, max_length=300, upload_to='contact_photos/%Y/%m'),
        ),
        migrations.AddField(
            model_name='contract',
            name='attachment_file',
            field=models.FileField(blank=True, max_length=300, upload_to='contract_attachments/%Y/%m'),
        ),
        migrations.AddField(
            model_name='customer',
            name='attachment_file',
            field=models.FileField(blank=True, max_length=300, upload_to='contract_attachments/%Y/%m'),
        ),
    ]
