# Generated by Django 5.2.15 on 2026-06-24 05:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_contactlog_photo_file_contract_attachment_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivedcustomersnapshot',
            options={'ordering': ['-archived_at', 'customer_no'], 'verbose_name': '客户归档快照', 'verbose_name_plural': '客户归档快照'},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': '操作审计', 'verbose_name_plural': '操作审计'},
        ),
        migrations.AlterModelOptions(
            name='contactlog',
            options={'ordering': ['-contact_at'], 'verbose_name': '跟进日志', 'verbose_name_plural': '跟进日志'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-signed_date', '-updated_at'], 'permissions': [('view_all_contracts', '可以查看全部合同')], 'verbose_name': '合同', 'verbose_name_plural': '合同'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-updated_at'], 'permissions': [('view_all_customers', '可以查看全部客户'), ('assign_customer', '可以分配客户')], 'verbose_name': '客户', 'verbose_name_plural': '客户'},
        ),
        migrations.AlterModelOptions(
            name='feishusyncrecord',
            options={'ordering': ['-last_seen_at'], 'verbose_name': '飞书同步记录', 'verbose_name_plural': '飞书同步记录'},
        ),
        migrations.AlterModelOptions(
            name='feishusyncsource',
            options={'ordering': ['name'], 'verbose_name': '飞书同步源', 'verbose_name_plural': '飞书同步源'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'permissions': [('view_all_leads', '可以查看全部线索'), ('assign_lead', '可以分配线索')], 'verbose_name': '线索', 'verbose_name_plural': '线索'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '员工权限', 'verbose_name_plural': '员工权限'},
        ),
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['due_at'], 'verbose_name': '跟进提醒', 'verbose_name_plural': '跟进提醒'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['category', 'name'], 'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterField(
            model_name='archivedcustomersnapshot',
            name='archived_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='归档时间'),
        ),
        migrations.AlterField(
            model_name='archivedcustomersnapshot',
            name='batch_id',
            field=models.CharField(db_index=True, max_length=64, verbose_name='批次标识'),
        ),
        migrations.AlterField(
            model_name='archivedcustomersnapshot',
            name='customer_no',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='客户编号'),
        ),
        migrations.AlterField(
            model_name='archivedcustomersnapshot',
            name='name',
            field=models.CharField(blank=True, max_length=160, verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='archivedcustomersnapshot',
            name='original_customer_id',
            field=models.BigIntegerField(verbose_name='原客户记录标识'),
        ),
        migrations.AlterField(
            model_name='archivedcustomersnapshot',
            name='payload',
            field=models.JSONField(default=dict, verbose_name='客户快照'),
        ),
        migrations.AlterField(
            model_name='archivedcustomersnapshot',
            name='reason',
            field=models.CharField(blank=True, max_length=160, verbose_name='归档原因'),
        ),
        migrations.AlterField(
            model_name='archivedcustomersnapshot',
            name='related_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='关联数据快照'),
        ),
        migrations.AlterField(
            model_name='archivedcustomersnapshot',
            name='source_kind',
            field=models.CharField(blank=True, max_length=20, verbose_name='资料类型'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=80, verbose_name='操作'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='detail',
            field=models.TextField(blank=True, verbose_name='详情'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_id',
            field=models.CharField(max_length=40, verbose_name='对象标识'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_type',
            field=models.CharField(max_length=40, verbose_name='对象类型'),
        ),
        migrations.AlterField(
            model_name='contactlog',
            name='contact_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='跟进时间'),
        ),
        migrations.AlterField(
            model_name='contactlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='contactlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_logs', to=settings.AUTH_USER_MODEL, verbose_name='系统创建人'),
        ),
        migrations.AlterField(
            model_name='contactlog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to='crm.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='contactlog',
            name='feishu_record_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='飞书记录标识'),
        ),
        migrations.AlterField(
            model_name='contactlog',
            name='feishu_source_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='飞书来源名称'),
        ),
        migrations.AlterField(
            model_name='contactlog',
            name='follower_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='跟进人'),
        ),
        migrations.AlterField(
            model_name='contactlog',
            name='method',
            field=models.CharField(choices=[('phone', '电话'), ('wechat', '微信'), ('email', '邮件'), ('visit', '拜访'), ('other', '其他')], default='wechat', max_length=20, verbose_name='跟进方式'),
        ),
        migrations.AlterField(
            model_name='contactlog',
            name='minutes_link',
            field=models.CharField(blank=True, max_length=300, verbose_name='音频文件'),
        ),
        migrations.AlterField(
            model_name='contactlog',
            name='next_contact_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下次联系时间'),
        ),
        migrations.AlterField(
            model_name='contactlog',
            name='photo_file',
            field=models.FileField(blank=True, max_length=300, upload_to='contact_photos/%Y/%m', verbose_name='跟进照片'),
        ),
        migrations.AlterField(
            model_name='contactlog',
            name='photo_note',
            field=models.TextField(blank=True, verbose_name='照片说明'),
        ),
        migrations.AlterField(
            model_name='contactlog',
            name='result',
            field=models.CharField(blank=True, max_length=160, verbose_name='跟进结果'),
        ),
        migrations.AlterField(
            model_name='contactlog',
            name='source',
            field=models.CharField(choices=[('manual', '人工录入'), ('xiaoquan', 'CRM助手整理'), ('feishu', '飞书同步'), ('import', '批量导入')], default='manual', max_length=20, verbose_name='记录来源'),
        ),
        migrations.AlterField(
            model_name='contactlog',
            name='summary',
            field=models.TextField(verbose_name='跟进内容'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='合同金额'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='attachment_file',
            field=models.FileField(blank=True, max_length=300, upload_to='contract_attachments/%Y/%m', verbose_name='合同附件'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='attachment_note',
            field=models.TextField(blank=True, verbose_name='附件说明'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_no',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='合同编号'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='系统创建人'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='crm.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='feishu_app_token',
            field=models.CharField(blank=True, max_length=128, verbose_name='飞书应用令牌'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='feishu_record_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='飞书记录标识'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='feishu_source_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='飞书来源名称'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='feishu_table_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='飞书表格标识'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有效'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_contracts', to=settings.AUTH_USER_MODEL, verbose_name='销售人员'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signed_by_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='销售人员名称'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signed_date',
            field=models.DateField(blank=True, null=True, verbose_name='签约日期'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_source',
            field=models.CharField(blank=True, max_length=80, verbose_name='账号来源'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='attachment_file',
            field=models.FileField(blank=True, max_length=300, upload_to='contract_attachments/%Y/%m', verbose_name='客户附件'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='attachment_note',
            field=models.TextField(blank=True, verbose_name='附件说明'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=80, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_position',
            field=models.CharField(blank=True, max_length=80, verbose_name='联系人职位'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='系统录入时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL, verbose_name='系统创建人'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='创建人名称'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_no',
            field=models.CharField(blank=True, max_length=32, unique=True, verbose_name='客户编号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_status_text',
            field=models.TextField(blank=True, verbose_name='客户状态'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, max_length=80, verbose_name='客户类型'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='demand',
            field=models.TextField(blank=True, verbose_name='客户需求'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='duplicate_checked',
            field=models.BooleanField(default=False, verbose_name='已检查重复'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='duplicate_customer_no',
            field=models.CharField(blank=True, max_length=64, verbose_name='重复客户编号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='feishu_app_token',
            field=models.CharField(blank=True, max_length=128, verbose_name='飞书应用令牌'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='feishu_record_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='飞书记录标识'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='feishu_source_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='飞书来源名称'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='feishu_table_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='飞书表格标识'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='grade',
            field=models.CharField(choices=[('incubating', '待孵化客户'), ('potential', '潜在客户'), ('normal', '一般客户'), ('intention', '意向客户'), ('key', '重点客户'), ('uncertain', '待定客户'), ('invalid', '无效客户')], default='potential', max_length=20, verbose_name='客户级别'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='historical_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='历史创建时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.FileField(blank=True, upload_to='customer_images/%Y/%m/', verbose_name='客户图片'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='industry',
            field=models.CharField(blank=True, max_length=120, verbose_name='行业'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有效'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_deal',
            field=models.BooleanField(default=False, verbose_name='成交状态'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_contact_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后联系时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lead_no',
            field=models.CharField(blank=True, max_length=64, verbose_name='线索编号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lead_status',
            field=models.CharField(blank=True, max_length=40, verbose_name='线索状态'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='legacy_customer_no',
            field=models.CharField(blank=True, max_length=64, verbose_name='历史客户编号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=160, verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='next_contact_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下次联系时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='沟通记录/备注'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='original_assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='原始分配时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='original_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='原始客户名称'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='客户经理'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='owner_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='客户经理名称'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=80, verbose_name='客户电话'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.CharField(blank=True, max_length=160, verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='related_lead',
            field=models.CharField(blank=True, max_length=120, verbose_name='关联线索'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='release_warned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='公海提醒时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source_channel',
            field=models.CharField(blank=True, max_length=80, verbose_name='线索来源'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source_kind',
            field=models.CharField(choices=[('lead', '线索'), ('customer', '客户')], default='customer', max_length=20, verbose_name='资料类型'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('private', '私有客户'), ('public', '公海客户'), ('invalid', '无效客户'), ('deal', '成交客户')], default='private', max_length=20, verbose_name='客户归属'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='customers', to='crm.tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wechat',
            field=models.CharField(blank=True, max_length=120, verbose_name='微信'),
        ),
        migrations.AlterField(
            model_name='feishusyncrecord',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, verbose_name='校验值'),
        ),
        migrations.AlterField(
            model_name='feishusyncrecord',
            name='contact_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feishu_sync_records', to='crm.contactlog', verbose_name='跟进日志'),
        ),
        migrations.AlterField(
            model_name='feishusyncrecord',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feishu_sync_records', to='crm.contract', verbose_name='合同'),
        ),
        migrations.AlterField(
            model_name='feishusyncrecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feishu_sync_records', to='crm.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='feishusyncrecord',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最近发现时间'),
        ),
        migrations.AlterField(
            model_name='feishusyncrecord',
            name='raw_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='原始字段'),
        ),
        migrations.AlterField(
            model_name='feishusyncrecord',
            name='record_id',
            field=models.CharField(max_length=64, verbose_name='记录标识'),
        ),
        migrations.AlterField(
            model_name='feishusyncrecord',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='crm.feishusyncsource', verbose_name='同步源'),
        ),
        migrations.AlterField(
            model_name='feishusyncsource',
            name='app_token',
            field=models.CharField(max_length=128, verbose_name='应用令牌'),
        ),
        migrations.AlterField(
            model_name='feishusyncsource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='feishusyncsource',
            name='default_record_kind',
            field=models.CharField(choices=[('lead', '线索'), ('customer', '客户')], default='lead', max_length=20, verbose_name='默认资料类型'),
        ),
        migrations.AlterField(
            model_name='feishusyncsource',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='feishusyncsource',
            name='field_mapping',
            field=models.JSONField(blank=True, default=dict, verbose_name='字段映射'),
        ),
        migrations.AlterField(
            model_name='feishusyncsource',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='最近错误'),
        ),
        migrations.AlterField(
            model_name='feishusyncsource',
            name='last_result',
            field=models.TextField(blank=True, verbose_name='最近结果'),
        ),
        migrations.AlterField(
            model_name='feishusyncsource',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近同步时间'),
        ),
        migrations.AlterField(
            model_name='feishusyncsource',
            name='name',
            field=models.CharField(max_length=120, verbose_name='来源名称'),
        ),
        migrations.AlterField(
            model_name='feishusyncsource',
            name='sheet_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='工作表标识'),
        ),
        migrations.AlterField(
            model_name='feishusyncsource',
            name='sheet_range',
            field=models.CharField(blank=True, max_length=64, verbose_name='工作表范围'),
        ),
        migrations.AlterField(
            model_name='feishusyncsource',
            name='source_kind',
            field=models.CharField(choices=[('customer', '客户/线索'), ('contact_log', '跟进记录'), ('contract', '合同')], default='customer', max_length=20, verbose_name='同步内容'),
        ),
        migrations.AlterField(
            model_name='feishusyncsource',
            name='source_type',
            field=models.CharField(choices=[('base', '多维表格'), ('sheet', '电子表格')], default='base', max_length=20, verbose_name='来源类型'),
        ),
        migrations.AlterField(
            model_name='feishusyncsource',
            name='table_id',
            field=models.CharField(max_length=64, verbose_name='表格标识'),
        ),
        migrations.AlterField(
            model_name='feishusyncsource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL, verbose_name='系统创建人'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='customer_type',
            field=models.CharField(blank=True, max_length=80, verbose_name='客户类型'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='demand',
            field=models.CharField(blank=True, max_length=160, verbose_name='客户需求'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.CharField(blank=True, max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有效'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_no',
            field=models.CharField(blank=True, max_length=32, unique=True, verbose_name='线索编号'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(blank=True, max_length=160, verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='next_contact_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下次联系时间'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=80, verbose_name='客户电话'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='region',
            field=models.CharField(blank=True, max_length=160, verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='related_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.customer', verbose_name='关联客户'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source_channel',
            field=models.CharField(blank=True, max_length=80, verbose_name='线索来源'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', '待确认'), ('assigned', '已分配'), ('converted', '已转客户'), ('duplicate', '重复'), ('invalid', '无效')], default='new', max_length=20, verbose_name='线索状态'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='leads', to='crm.tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='wechat',
            field=models.CharField(blank=True, max_length=120, verbose_name='微信'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='feishu_open_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='飞书用户标识'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('leader', '领导'), ('sales', '销售'), ('marketing', '新媒体')], default='sales', max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='crm.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='due_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='提醒时间'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='crm.lead', verbose_name='线索'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='message',
            field=models.TextField(verbose_name='提醒内容'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('next_contact', '到期跟进'), ('public_pool_warning', '公海释放提醒'), ('public_pool_released', '已进入公海')], max_length=32, verbose_name='提醒类型'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('pending', '待提醒'), ('sent', '已发送'), ('done', '已完成')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(blank=True, max_length=32, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='标签名称'),
        ),
    ]
