# Generated by Django 5.2.15 on 2026-06-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_archivedcustomersnapshot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('next_contact', '到期跟进'), ('uncontacted_rule', '未联系提醒'), ('protected_customer_idle', '报价/成交客户未联系提醒'), ('public_pool_warning', '公海释放提醒'), ('public_pool_released', '已进入公海')], max_length=32, verbose_name='提醒类型'),
        ),
    ]
